name: FunEnchantments
version: '1.0'
main: ru.funenchantments.FunEnchantments
api-version: '1.16'
authors: [wryuin]
description: CustomEnchantments
commands:
  funenchantments:
    description: Выдать enchanted книгу или кирку
    usage: /giveenchanted <player> [book|diamond_pickaxe|netherite_pickaxe]
    permission: funenchantments.command
permissions:
  funenchantments.command:
    description: Разрешение на использование команды /giveenchanted
    default: op